// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: mymoney/mymoney.proto

package mymoney

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyMoneyService_GetPaymentLink_FullMethodName = "/mymoney.MyMoneyService/GetPaymentLink"
)

// MyMoneyServiceClient is the client API for MyMoneyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// mymoney responsibility
type MyMoneyServiceClient interface {
	GetPaymentLink(ctx context.Context, in *PaymentLinkRequest, opts ...grpc.CallOption) (*PaymentLinkResponse, error)
}

type myMoneyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyMoneyServiceClient(cc grpc.ClientConnInterface) MyMoneyServiceClient {
	return &myMoneyServiceClient{cc}
}

func (c *myMoneyServiceClient) GetPaymentLink(ctx context.Context, in *PaymentLinkRequest, opts ...grpc.CallOption) (*PaymentLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentLinkResponse)
	err := c.cc.Invoke(ctx, MyMoneyService_GetPaymentLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyMoneyServiceServer is the server API for MyMoneyService service.
// All implementations must embed UnimplementedMyMoneyServiceServer
// for forward compatibility.
//
// mymoney responsibility
type MyMoneyServiceServer interface {
	GetPaymentLink(context.Context, *PaymentLinkRequest) (*PaymentLinkResponse, error)
	mustEmbedUnimplementedMyMoneyServiceServer()
}

// UnimplementedMyMoneyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyMoneyServiceServer struct{}

func (UnimplementedMyMoneyServiceServer) GetPaymentLink(context.Context, *PaymentLinkRequest) (*PaymentLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentLink not implemented")
}
func (UnimplementedMyMoneyServiceServer) mustEmbedUnimplementedMyMoneyServiceServer() {}
func (UnimplementedMyMoneyServiceServer) testEmbeddedByValue()                        {}

// UnsafeMyMoneyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyMoneyServiceServer will
// result in compilation errors.
type UnsafeMyMoneyServiceServer interface {
	mustEmbedUnimplementedMyMoneyServiceServer()
}

func RegisterMyMoneyServiceServer(s grpc.ServiceRegistrar, srv MyMoneyServiceServer) {
	// If the following call panics, it indicates UnimplementedMyMoneyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyMoneyService_ServiceDesc, srv)
}

func _MyMoneyService_GetPaymentLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyMoneyServiceServer).GetPaymentLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyMoneyService_GetPaymentLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyMoneyServiceServer).GetPaymentLink(ctx, req.(*PaymentLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MyMoneyService_ServiceDesc is the grpc.ServiceDesc for MyMoneyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyMoneyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mymoney.MyMoneyService",
	HandlerType: (*MyMoneyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentLink",
			Handler:    _MyMoneyService_GetPaymentLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mymoney/mymoney.proto",
}

const (
	MyMoneyCallbackService_OnPaymentComplete_FullMethodName = "/mymoney.MyMoneyCallbackService/OnPaymentComplete"
)

// MyMoneyCallbackServiceClient is the client API for MyMoneyCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// carsharing responsibility
type MyMoneyCallbackServiceClient interface {
	OnPaymentComplete(ctx context.Context, in *WebhookNotify, opts ...grpc.CallOption) (*WebhookResponse, error)
}

type myMoneyCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyMoneyCallbackServiceClient(cc grpc.ClientConnInterface) MyMoneyCallbackServiceClient {
	return &myMoneyCallbackServiceClient{cc}
}

func (c *myMoneyCallbackServiceClient) OnPaymentComplete(ctx context.Context, in *WebhookNotify, opts ...grpc.CallOption) (*WebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookResponse)
	err := c.cc.Invoke(ctx, MyMoneyCallbackService_OnPaymentComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyMoneyCallbackServiceServer is the server API for MyMoneyCallbackService service.
// All implementations must embed UnimplementedMyMoneyCallbackServiceServer
// for forward compatibility.
//
// carsharing responsibility
type MyMoneyCallbackServiceServer interface {
	OnPaymentComplete(context.Context, *WebhookNotify) (*WebhookResponse, error)
	mustEmbedUnimplementedMyMoneyCallbackServiceServer()
}

// UnimplementedMyMoneyCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyMoneyCallbackServiceServer struct{}

func (UnimplementedMyMoneyCallbackServiceServer) OnPaymentComplete(context.Context, *WebhookNotify) (*WebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnPaymentComplete not implemented")
}
func (UnimplementedMyMoneyCallbackServiceServer) mustEmbedUnimplementedMyMoneyCallbackServiceServer() {
}
func (UnimplementedMyMoneyCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeMyMoneyCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyMoneyCallbackServiceServer will
// result in compilation errors.
type UnsafeMyMoneyCallbackServiceServer interface {
	mustEmbedUnimplementedMyMoneyCallbackServiceServer()
}

func RegisterMyMoneyCallbackServiceServer(s grpc.ServiceRegistrar, srv MyMoneyCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedMyMoneyCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyMoneyCallbackService_ServiceDesc, srv)
}

func _MyMoneyCallbackService_OnPaymentComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyMoneyCallbackServiceServer).OnPaymentComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyMoneyCallbackService_OnPaymentComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyMoneyCallbackServiceServer).OnPaymentComplete(ctx, req.(*WebhookNotify))
	}
	return interceptor(ctx, in, info, handler)
}

// MyMoneyCallbackService_ServiceDesc is the grpc.ServiceDesc for MyMoneyCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyMoneyCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mymoney.MyMoneyCallbackService",
	HandlerType: (*MyMoneyCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnPaymentComplete",
			Handler:    _MyMoneyCallbackService_OnPaymentComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mymoney/mymoney.proto",
}
