// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mymoney/mymoney.proto

package mymoney

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     int64                  `protobuf:"varint,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	AmountInCents int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkRequest) Reset() {
	*x = PaymentLinkRequest{}
	mi := &file_mymoney_mymoney_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkRequest) ProtoMessage() {}

func (x *PaymentLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mymoney_mymoney_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkRequest.ProtoReflect.Descriptor instead.
func (*PaymentLinkRequest) Descriptor() ([]byte, []int) {
	return file_mymoney_mymoney_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentLinkRequest) GetInvoiceId() int64 {
	if x != nil {
		return x.InvoiceId
	}
	return 0
}

func (x *PaymentLinkRequest) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *PaymentLinkRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type PaymentLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentUrl    string                 `protobuf:"bytes,1,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentLinkResponse) Reset() {
	*x = PaymentLinkResponse{}
	mi := &file_mymoney_mymoney_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentLinkResponse) ProtoMessage() {}

func (x *PaymentLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mymoney_mymoney_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentLinkResponse.ProtoReflect.Descriptor instead.
func (*PaymentLinkResponse) Descriptor() ([]byte, []int) {
	return file_mymoney_mymoney_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentLinkResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *PaymentLinkResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type WebhookNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     int64                  `protobuf:"varint,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	AmountInCents int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "success" / "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookNotify) Reset() {
	*x = WebhookNotify{}
	mi := &file_mymoney_mymoney_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookNotify) ProtoMessage() {}

func (x *WebhookNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mymoney_mymoney_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookNotify.ProtoReflect.Descriptor instead.
func (*WebhookNotify) Descriptor() ([]byte, []int) {
	return file_mymoney_mymoney_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookNotify) GetInvoiceId() int64 {
	if x != nil {
		return x.InvoiceId
	}
	return 0
}

func (x *WebhookNotify) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *WebhookNotify) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *WebhookNotify) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookResponse) Reset() {
	*x = WebhookResponse{}
	mi := &file_mymoney_mymoney_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookResponse) ProtoMessage() {}

func (x *WebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mymoney_mymoney_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookResponse.ProtoReflect.Descriptor instead.
func (*WebhookResponse) Descriptor() ([]byte, []int) {
	return file_mymoney_mymoney_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_mymoney_mymoney_proto protoreflect.FileDescriptor

const file_mymoney_mymoney_proto_rawDesc = "" +
	"\n" +
	"\x15mymoney/mymoney.proto\x12\amymoney\"~\n" +
	"\x12PaymentLinkRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\x03R\tinvoiceId\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12!\n" +
	"\fcallback_url\x18\x03 \x01(\tR\vcallbackUrl\"U\n" +
	"\x13PaymentLinkResponse\x12\x1f\n" +
	"\vpayment_url\x18\x01 \x01(\tR\n" +
	"paymentUrl\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"\x8d\x01\n" +
	"\rWebhookNotify\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\x03R\tinvoiceId\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"-\n" +
	"\x0fWebhookResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2]\n" +
	"\x0eMyMoneyService\x12K\n" +
	"\x0eGetPaymentLink\x12\x1b.mymoney.PaymentLinkRequest\x1a\x1c.mymoney.PaymentLinkResponse2_\n" +
	"\x16MyMoneyCallbackService\x12E\n" +
	"\x11OnPaymentComplete\x12\x16.mymoney.WebhookNotify\x1a\x18.mymoney.WebhookResponseB6Z4github.com/SternKater/carsharing/pkg/mymoney;mymoneyb\x06proto3"

var (
	file_mymoney_mymoney_proto_rawDescOnce sync.Once
	file_mymoney_mymoney_proto_rawDescData []byte
)

func file_mymoney_mymoney_proto_rawDescGZIP() []byte {
	file_mymoney_mymoney_proto_rawDescOnce.Do(func() {
		file_mymoney_mymoney_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mymoney_mymoney_proto_rawDesc), len(file_mymoney_mymoney_proto_rawDesc)))
	})
	return file_mymoney_mymoney_proto_rawDescData
}

var file_mymoney_mymoney_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mymoney_mymoney_proto_goTypes = []any{
	(*PaymentLinkRequest)(nil),  // 0: mymoney.PaymentLinkRequest
	(*PaymentLinkResponse)(nil), // 1: mymoney.PaymentLinkResponse
	(*WebhookNotify)(nil),       // 2: mymoney.WebhookNotify
	(*WebhookResponse)(nil),     // 3: mymoney.WebhookResponse
}
var file_mymoney_mymoney_proto_depIdxs = []int32{
	0, // 0: mymoney.MyMoneyService.GetPaymentLink:input_type -> mymoney.PaymentLinkRequest
	2, // 1: mymoney.MyMoneyCallbackService.OnPaymentComplete:input_type -> mymoney.WebhookNotify
	1, // 2: mymoney.MyMoneyService.GetPaymentLink:output_type -> mymoney.PaymentLinkResponse
	3, // 3: mymoney.MyMoneyCallbackService.OnPaymentComplete:output_type -> mymoney.WebhookResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mymoney_mymoney_proto_init() }
func file_mymoney_mymoney_proto_init() {
	if File_mymoney_mymoney_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mymoney_mymoney_proto_rawDesc), len(file_mymoney_mymoney_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mymoney_mymoney_proto_goTypes,
		DependencyIndexes: file_mymoney_mymoney_proto_depIdxs,
		MessageInfos:      file_mymoney_mymoney_proto_msgTypes,
	}.Build()
	File_mymoney_mymoney_proto = out.File
	file_mymoney_mymoney_proto_goTypes = nil
	file_mymoney_mymoney_proto_depIdxs = nil
}
