// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/wallet/deposit.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId      int64                  `protobuf:"varint,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	AmountInCents  int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_billing_wallet_deposit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_wallet_deposit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_billing_wallet_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *DepositRequest) GetInvoiceId() int64 {
	if x != nil {
		return x.InvoiceId
	}
	return 0
}

func (x *DepositRequest) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *DepositRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AmountInCents int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_billing_wallet_deposit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_wallet_deposit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_billing_wallet_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *DepositResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DepositResponse) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *DepositResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_billing_wallet_deposit_proto protoreflect.FileDescriptor

const file_billing_wallet_deposit_proto_rawDesc = "" +
	"\n" +
	"\x1cbilling/wallet/deposit.proto\x12\x06wallet\"\x80\x01\n" +
	"\x0eDepositRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\x03R\tinvoiceId\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"m\n" +
	"\x0fDepositResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2L\n" +
	"\x0eDepositService\x12:\n" +
	"\aDeposit\x12\x16.wallet.DepositRequest\x1a\x17.wallet.DepositResponseBDZBgithub.com/SternKater/carsharing/pkg/billing/wallet/deposit;walletb\x06proto3"

var (
	file_billing_wallet_deposit_proto_rawDescOnce sync.Once
	file_billing_wallet_deposit_proto_rawDescData []byte
)

func file_billing_wallet_deposit_proto_rawDescGZIP() []byte {
	file_billing_wallet_deposit_proto_rawDescOnce.Do(func() {
		file_billing_wallet_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_wallet_deposit_proto_rawDesc), len(file_billing_wallet_deposit_proto_rawDesc)))
	})
	return file_billing_wallet_deposit_proto_rawDescData
}

var file_billing_wallet_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_wallet_deposit_proto_goTypes = []any{
	(*DepositRequest)(nil),  // 0: wallet.DepositRequest
	(*DepositResponse)(nil), // 1: wallet.DepositResponse
}
var file_billing_wallet_deposit_proto_depIdxs = []int32{
	0, // 0: wallet.DepositService.Deposit:input_type -> wallet.DepositRequest
	1, // 1: wallet.DepositService.Deposit:output_type -> wallet.DepositResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_wallet_deposit_proto_init() }
func file_billing_wallet_deposit_proto_init() {
	if File_billing_wallet_deposit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_wallet_deposit_proto_rawDesc), len(file_billing_wallet_deposit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_wallet_deposit_proto_goTypes,
		DependencyIndexes: file_billing_wallet_deposit_proto_depIdxs,
		MessageInfos:      file_billing_wallet_deposit_proto_msgTypes,
	}.Build()
	File_billing_wallet_deposit_proto = out.File
	file_billing_wallet_deposit_proto_goTypes = nil
	file_billing_wallet_deposit_proto_depIdxs = nil
}
