// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/history/history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartFrom     int64                  `protobuf:"varint,1,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	EndTo         int64                  `protobuf:"varint,2,opt,name=end_to,json=endTo,proto3" json:"end_to,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_billing_history_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_history_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_billing_history_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRequest) GetStartFrom() int64 {
	if x != nil {
		return x.StartFrom
	}
	return 0
}

func (x *HistoryRequest) GetEndTo() int64 {
	if x != nil {
		return x.EndTo
	}
	return 0
}

func (x *HistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type HistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AmountInCents int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_billing_history_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_history_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_billing_history_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HistoryItem) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *HistoryItem) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type HistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items              []*HistoryItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmountInCents int32                  `protobuf:"varint,4,opt,name=total_amount_in_cents,json=totalAmountInCents,proto3" json:"total_amount_in_cents,omitempty"`
	CurrentPage        int32                  `protobuf:"varint,5,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_billing_history_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_history_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_billing_history_history_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HistoryResponse) GetItems() []*HistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *HistoryResponse) GetTotalAmountInCents() int32 {
	if x != nil {
		return x.TotalAmountInCents
	}
	return 0
}

func (x *HistoryResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

var File_billing_history_history_proto protoreflect.FileDescriptor

const file_billing_history_history_proto_rawDesc = "" +
	"\n" +
	"\x1dbilling/history/history.proto\x12\ahistory\"Z\n" +
	"\x0eHistoryRequest\x12\x1d\n" +
	"\n" +
	"start_from\x18\x01 \x01(\x03R\tstartFrom\x12\x15\n" +
	"\x06end_to\x18\x02 \x01(\x03R\x05endTo\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"m\n" +
	"\vHistoryItem\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\xc7\x01\n" +
	"\x0fHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.history.HistoryItemR\x05items\x121\n" +
	"\x15total_amount_in_cents\x18\x04 \x01(\x05R\x12totalAmountInCents\x12!\n" +
	"\fcurrent_page\x18\x05 \x01(\x05R\vcurrentPage2N\n" +
	"\x0eHistoryService\x12<\n" +
	"\aHistory\x12\x17.history.HistoryRequest\x1a\x18.history.HistoryResponseB>Z<github.com/SternKater/carsharing/pkg/billing/history;historyb\x06proto3"

var (
	file_billing_history_history_proto_rawDescOnce sync.Once
	file_billing_history_history_proto_rawDescData []byte
)

func file_billing_history_history_proto_rawDescGZIP() []byte {
	file_billing_history_history_proto_rawDescOnce.Do(func() {
		file_billing_history_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_history_history_proto_rawDesc), len(file_billing_history_history_proto_rawDesc)))
	})
	return file_billing_history_history_proto_rawDescData
}

var file_billing_history_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_billing_history_history_proto_goTypes = []any{
	(*HistoryRequest)(nil),  // 0: history.HistoryRequest
	(*HistoryItem)(nil),     // 1: history.HistoryItem
	(*HistoryResponse)(nil), // 2: history.HistoryResponse
}
var file_billing_history_history_proto_depIdxs = []int32{
	1, // 0: history.HistoryResponse.items:type_name -> history.HistoryItem
	0, // 1: history.HistoryService.History:input_type -> history.HistoryRequest
	2, // 2: history.HistoryService.History:output_type -> history.HistoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_billing_history_history_proto_init() }
func file_billing_history_history_proto_init() {
	if File_billing_history_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_history_history_proto_rawDesc), len(file_billing_history_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_history_history_proto_goTypes,
		DependencyIndexes: file_billing_history_history_proto_depIdxs,
		MessageInfos:      file_billing_history_history_proto_msgTypes,
	}.Build()
	File_billing_history_history_proto = out.File
	file_billing_history_history_proto_goTypes = nil
	file_billing_history_history_proto_depIdxs = nil
}
