// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/invoice/pay.proto

package invoice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId      int64                  `protobuf:"varint,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	AmountInCents  int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_billing_invoice_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoice_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_billing_invoice_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayRequest) GetInvoiceId() int64 {
	if x != nil {
		return x.InvoiceId
	}
	return 0
}

func (x *PayRequest) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *PayRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AmountInCents int64                  `protobuf:"varint,2,opt,name=amount_in_cents,json=amountInCents,proto3" json:"amount_in_cents,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_billing_invoice_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_invoice_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_billing_invoice_pay_proto_rawDescGZIP(), []int{1}
}

func (x *PayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayResponse) GetAmountInCents() int64 {
	if x != nil {
		return x.AmountInCents
	}
	return 0
}

func (x *PayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_billing_invoice_pay_proto protoreflect.FileDescriptor

const file_billing_invoice_pay_proto_rawDesc = "" +
	"\n" +
	"\x19billing/invoice/pay.proto\x12\ainvoice\"|\n" +
	"\n" +
	"PayRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\x03R\tinvoiceId\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"i\n" +
	"\vPayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0famount_in_cents\x18\x02 \x01(\x03R\ramountInCents\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2>\n" +
	"\n" +
	"PayService\x120\n" +
	"\x03Pay\x12\x13.invoice.PayRequest\x1a\x14.invoice.PayResponseBBZ@github.com/SternKater/carsharing/pkg/billing/invoice/pay;invoiceb\x06proto3"

var (
	file_billing_invoice_pay_proto_rawDescOnce sync.Once
	file_billing_invoice_pay_proto_rawDescData []byte
)

func file_billing_invoice_pay_proto_rawDescGZIP() []byte {
	file_billing_invoice_pay_proto_rawDescOnce.Do(func() {
		file_billing_invoice_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_invoice_pay_proto_rawDesc), len(file_billing_invoice_pay_proto_rawDesc)))
	})
	return file_billing_invoice_pay_proto_rawDescData
}

var file_billing_invoice_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_invoice_pay_proto_goTypes = []any{
	(*PayRequest)(nil),  // 0: invoice.PayRequest
	(*PayResponse)(nil), // 1: invoice.PayResponse
}
var file_billing_invoice_pay_proto_depIdxs = []int32{
	0, // 0: invoice.PayService.Pay:input_type -> invoice.PayRequest
	1, // 1: invoice.PayService.Pay:output_type -> invoice.PayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_invoice_pay_proto_init() }
func file_billing_invoice_pay_proto_init() {
	if File_billing_invoice_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_invoice_pay_proto_rawDesc), len(file_billing_invoice_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_invoice_pay_proto_goTypes,
		DependencyIndexes: file_billing_invoice_pay_proto_depIdxs,
		MessageInfos:      file_billing_invoice_pay_proto_msgTypes,
	}.Build()
	File_billing_invoice_pay_proto = out.File
	file_billing_invoice_pay_proto_goTypes = nil
	file_billing_invoice_pay_proto_depIdxs = nil
}
