// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cars/cars.proto

package cars

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarsRequest) Reset() {
	*x = CarsRequest{}
	mi := &file_cars_cars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarsRequest) ProtoMessage() {}

func (x *CarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_cars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarsRequest.ProtoReflect.Descriptor instead.
func (*CarsRequest) Descriptor() ([]byte, []int) {
	return file_cars_cars_proto_rawDescGZIP(), []int{0}
}

type CarsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Ppm           int64                  `protobuf:"varint,4,opt,name=ppm,proto3" json:"ppm,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarsItem) Reset() {
	*x = CarsItem{}
	mi := &file_cars_cars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarsItem) ProtoMessage() {}

func (x *CarsItem) ProtoReflect() protoreflect.Message {
	mi := &file_cars_cars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarsItem.ProtoReflect.Descriptor instead.
func (*CarsItem) Descriptor() ([]byte, []int) {
	return file_cars_cars_proto_rawDescGZIP(), []int{1}
}

func (x *CarsItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CarsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CarsItem) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CarsItem) GetPpm() int64 {
	if x != nil {
		return x.Ppm
	}
	return 0
}

func (x *CarsItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cars          []*CarsItem            `protobuf:"bytes,3,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarsResponse) Reset() {
	*x = CarsResponse{}
	mi := &file_cars_cars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarsResponse) ProtoMessage() {}

func (x *CarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_cars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarsResponse.ProtoReflect.Descriptor instead.
func (*CarsResponse) Descriptor() ([]byte, []int) {
	return file_cars_cars_proto_rawDescGZIP(), []int{2}
}

func (x *CarsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CarsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CarsResponse) GetCars() []*CarsItem {
	if x != nil {
		return x.Cars
	}
	return nil
}

var File_cars_cars_proto protoreflect.FileDescriptor

const file_cars_cars_proto_rawDesc = "" +
	"\n" +
	"\x0fcars/cars.proto\x12\x04cars\"\r\n" +
	"\vCarsRequest\"p\n" +
	"\bCarsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x10\n" +
	"\x03ppm\x18\x04 \x01(\x03R\x03ppm\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"f\n" +
	"\fCarsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04cars\x18\x03 \x03(\v2\x0e.cars.CarsItemR\x04cars2<\n" +
	"\vCarsService\x12-\n" +
	"\x04Cars\x12\x11.cars.CarsRequest\x1a\x12.cars.CarsResponseB0Z.github.com/SternKater/carsharing/pkg/cars;carsb\x06proto3"

var (
	file_cars_cars_proto_rawDescOnce sync.Once
	file_cars_cars_proto_rawDescData []byte
)

func file_cars_cars_proto_rawDescGZIP() []byte {
	file_cars_cars_proto_rawDescOnce.Do(func() {
		file_cars_cars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cars_cars_proto_rawDesc), len(file_cars_cars_proto_rawDesc)))
	})
	return file_cars_cars_proto_rawDescData
}

var file_cars_cars_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cars_cars_proto_goTypes = []any{
	(*CarsRequest)(nil),  // 0: cars.CarsRequest
	(*CarsItem)(nil),     // 1: cars.CarsItem
	(*CarsResponse)(nil), // 2: cars.CarsResponse
}
var file_cars_cars_proto_depIdxs = []int32{
	1, // 0: cars.CarsResponse.cars:type_name -> cars.CarsItem
	0, // 1: cars.CarsService.Cars:input_type -> cars.CarsRequest
	2, // 2: cars.CarsService.Cars:output_type -> cars.CarsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cars_cars_proto_init() }
func file_cars_cars_proto_init() {
	if File_cars_cars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cars_cars_proto_rawDesc), len(file_cars_cars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cars_cars_proto_goTypes,
		DependencyIndexes: file_cars_cars_proto_depIdxs,
		MessageInfos:      file_cars_cars_proto_msgTypes,
	}.Build()
	File_cars_cars_proto = out.File
	file_cars_cars_proto_goTypes = nil
	file_cars_cars_proto_depIdxs = nil
}
