// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: cars/cars.proto

package cars

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CarsService_Cars_FullMethodName = "/cars.CarsService/Cars"
)

// CarsServiceClient is the client API for CarsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarsServiceClient interface {
	Cars(ctx context.Context, in *CarsRequest, opts ...grpc.CallOption) (*CarsResponse, error)
}

type carsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarsServiceClient(cc grpc.ClientConnInterface) CarsServiceClient {
	return &carsServiceClient{cc}
}

func (c *carsServiceClient) Cars(ctx context.Context, in *CarsRequest, opts ...grpc.CallOption) (*CarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CarsResponse)
	err := c.cc.Invoke(ctx, CarsService_Cars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarsServiceServer is the server API for CarsService service.
// All implementations must embed UnimplementedCarsServiceServer
// for forward compatibility.
type CarsServiceServer interface {
	Cars(context.Context, *CarsRequest) (*CarsResponse, error)
	mustEmbedUnimplementedCarsServiceServer()
}

// UnimplementedCarsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCarsServiceServer struct{}

func (UnimplementedCarsServiceServer) Cars(context.Context, *CarsRequest) (*CarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cars not implemented")
}
func (UnimplementedCarsServiceServer) mustEmbedUnimplementedCarsServiceServer() {}
func (UnimplementedCarsServiceServer) testEmbeddedByValue()                     {}

// UnsafeCarsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarsServiceServer will
// result in compilation errors.
type UnsafeCarsServiceServer interface {
	mustEmbedUnimplementedCarsServiceServer()
}

func RegisterCarsServiceServer(s grpc.ServiceRegistrar, srv CarsServiceServer) {
	// If the following call panics, it indicates UnimplementedCarsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CarsService_ServiceDesc, srv)
}

func _CarsService_Cars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarsServiceServer).Cars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarsService_Cars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarsServiceServer).Cars(ctx, req.(*CarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarsService_ServiceDesc is the grpc.ServiceDesc for CarsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cars.CarsService",
	HandlerType: (*CarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cars",
			Handler:    _CarsService_Cars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cars/cars.proto",
}
